//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TK_Cons_F_v0.DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class tableClassify
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tableClassify()
        {
            this.tableErrorLogs = new HashSet<tableErrorLog>();
        }
    
        public int ClsID { get; set; }
        public Nullable<int> altLim { get; set; }
        public Nullable<int> ustLim { get; set; }
        public Nullable<int> birLim { get; set; }
        public string someText { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tableErrorLog> tableErrorLogs { get; set; }
    }
}
