// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: mydataset.proto

package my.classes;

public final class MyDataSet {
  private MyDataSet() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SingleDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:SingleData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string someText = 1;</code>
     */
    java.lang.String getSomeText();
    /**
     * <code>string someText = 1;</code>
     */
    com.google.protobuf.ByteString
        getSomeTextBytes();

    /**
     * <code>int32 someValue = 2;</code>
     */
    int getSomeValue();

    /**
     * <code>int64 timeSeconds = 3;</code>
     */
    long getTimeSeconds();
  }
  /**
   * Protobuf type {@code SingleData}
   */
  public  static final class SingleData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:SingleData)
      SingleDataOrBuilder {
    // Use SingleData.newBuilder() to construct.
    private SingleData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SingleData() {
      someText_ = "";
      someValue_ = 0;
      timeSeconds_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private SingleData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              someText_ = s;
              break;
            }
            case 16: {

              someValue_ = input.readInt32();
              break;
            }
            case 24: {

              timeSeconds_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return my.classes.MyDataSet.internal_static_SingleData_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return my.classes.MyDataSet.internal_static_SingleData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              my.classes.MyDataSet.SingleData.class, my.classes.MyDataSet.SingleData.Builder.class);
    }

    public static final int SOMETEXT_FIELD_NUMBER = 1;
    private volatile java.lang.Object someText_;
    /**
     * <code>string someText = 1;</code>
     */
    public java.lang.String getSomeText() {
      java.lang.Object ref = someText_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        someText_ = s;
        return s;
      }
    }
    /**
     * <code>string someText = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSomeTextBytes() {
      java.lang.Object ref = someText_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        someText_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOMEVALUE_FIELD_NUMBER = 2;
    private int someValue_;
    /**
     * <code>int32 someValue = 2;</code>
     */
    public int getSomeValue() {
      return someValue_;
    }

    public static final int TIMESECONDS_FIELD_NUMBER = 3;
    private long timeSeconds_;
    /**
     * <code>int64 timeSeconds = 3;</code>
     */
    public long getTimeSeconds() {
      return timeSeconds_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSomeTextBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, someText_);
      }
      if (someValue_ != 0) {
        output.writeInt32(2, someValue_);
      }
      if (timeSeconds_ != 0L) {
        output.writeInt64(3, timeSeconds_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSomeTextBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, someText_);
      }
      if (someValue_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, someValue_);
      }
      if (timeSeconds_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, timeSeconds_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof my.classes.MyDataSet.SingleData)) {
        return super.equals(obj);
      }
      my.classes.MyDataSet.SingleData other = (my.classes.MyDataSet.SingleData) obj;

      boolean result = true;
      result = result && getSomeText()
          .equals(other.getSomeText());
      result = result && (getSomeValue()
          == other.getSomeValue());
      result = result && (getTimeSeconds()
          == other.getTimeSeconds());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SOMETEXT_FIELD_NUMBER;
      hash = (53 * hash) + getSomeText().hashCode();
      hash = (37 * hash) + SOMEVALUE_FIELD_NUMBER;
      hash = (53 * hash) + getSomeValue();
      hash = (37 * hash) + TIMESECONDS_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTimeSeconds());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static my.classes.MyDataSet.SingleData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static my.classes.MyDataSet.SingleData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static my.classes.MyDataSet.SingleData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static my.classes.MyDataSet.SingleData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(my.classes.MyDataSet.SingleData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code SingleData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:SingleData)
        my.classes.MyDataSet.SingleDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return my.classes.MyDataSet.internal_static_SingleData_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return my.classes.MyDataSet.internal_static_SingleData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                my.classes.MyDataSet.SingleData.class, my.classes.MyDataSet.SingleData.Builder.class);
      }

      // Construct using my.classes.MyDataSet.SingleData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        someText_ = "";

        someValue_ = 0;

        timeSeconds_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return my.classes.MyDataSet.internal_static_SingleData_descriptor;
      }

      public my.classes.MyDataSet.SingleData getDefaultInstanceForType() {
        return my.classes.MyDataSet.SingleData.getDefaultInstance();
      }

      public my.classes.MyDataSet.SingleData build() {
        my.classes.MyDataSet.SingleData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public my.classes.MyDataSet.SingleData buildPartial() {
        my.classes.MyDataSet.SingleData result = new my.classes.MyDataSet.SingleData(this);
        result.someText_ = someText_;
        result.someValue_ = someValue_;
        result.timeSeconds_ = timeSeconds_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof my.classes.MyDataSet.SingleData) {
          return mergeFrom((my.classes.MyDataSet.SingleData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(my.classes.MyDataSet.SingleData other) {
        if (other == my.classes.MyDataSet.SingleData.getDefaultInstance()) return this;
        if (!other.getSomeText().isEmpty()) {
          someText_ = other.someText_;
          onChanged();
        }
        if (other.getSomeValue() != 0) {
          setSomeValue(other.getSomeValue());
        }
        if (other.getTimeSeconds() != 0L) {
          setTimeSeconds(other.getTimeSeconds());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        my.classes.MyDataSet.SingleData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (my.classes.MyDataSet.SingleData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object someText_ = "";
      /**
       * <code>string someText = 1;</code>
       */
      public java.lang.String getSomeText() {
        java.lang.Object ref = someText_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          someText_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string someText = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSomeTextBytes() {
        java.lang.Object ref = someText_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          someText_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string someText = 1;</code>
       */
      public Builder setSomeText(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        someText_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string someText = 1;</code>
       */
      public Builder clearSomeText() {
        
        someText_ = getDefaultInstance().getSomeText();
        onChanged();
        return this;
      }
      /**
       * <code>string someText = 1;</code>
       */
      public Builder setSomeTextBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        someText_ = value;
        onChanged();
        return this;
      }

      private int someValue_ ;
      /**
       * <code>int32 someValue = 2;</code>
       */
      public int getSomeValue() {
        return someValue_;
      }
      /**
       * <code>int32 someValue = 2;</code>
       */
      public Builder setSomeValue(int value) {
        
        someValue_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 someValue = 2;</code>
       */
      public Builder clearSomeValue() {
        
        someValue_ = 0;
        onChanged();
        return this;
      }

      private long timeSeconds_ ;
      /**
       * <code>int64 timeSeconds = 3;</code>
       */
      public long getTimeSeconds() {
        return timeSeconds_;
      }
      /**
       * <code>int64 timeSeconds = 3;</code>
       */
      public Builder setTimeSeconds(long value) {
        
        timeSeconds_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 timeSeconds = 3;</code>
       */
      public Builder clearTimeSeconds() {
        
        timeSeconds_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:SingleData)
    }

    // @@protoc_insertion_point(class_scope:SingleData)
    private static final my.classes.MyDataSet.SingleData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new my.classes.MyDataSet.SingleData();
    }

    public static my.classes.MyDataSet.SingleData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<SingleData>
        PARSER = new com.google.protobuf.AbstractParser<SingleData>() {
      public SingleData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new SingleData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SingleData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SingleData> getParserForType() {
      return PARSER;
    }

    public my.classes.MyDataSet.SingleData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DataSetOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DataSet)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    java.util.List<my.classes.MyDataSet.SingleData> 
        getSingleDataList();
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    my.classes.MyDataSet.SingleData getSingleData(int index);
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    int getSingleDataCount();
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    java.util.List<? extends my.classes.MyDataSet.SingleDataOrBuilder> 
        getSingleDataOrBuilderList();
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    my.classes.MyDataSet.SingleDataOrBuilder getSingleDataOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code DataSet}
   */
  public  static final class DataSet extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DataSet)
      DataSetOrBuilder {
    // Use DataSet.newBuilder() to construct.
    private DataSet(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DataSet() {
      singleData_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private DataSet(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                singleData_ = new java.util.ArrayList<my.classes.MyDataSet.SingleData>();
                mutable_bitField0_ |= 0x00000001;
              }
              singleData_.add(
                  input.readMessage(my.classes.MyDataSet.SingleData.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          singleData_ = java.util.Collections.unmodifiableList(singleData_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return my.classes.MyDataSet.internal_static_DataSet_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return my.classes.MyDataSet.internal_static_DataSet_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              my.classes.MyDataSet.DataSet.class, my.classes.MyDataSet.DataSet.Builder.class);
    }

    public static final int SINGLEDATA_FIELD_NUMBER = 1;
    private java.util.List<my.classes.MyDataSet.SingleData> singleData_;
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    public java.util.List<my.classes.MyDataSet.SingleData> getSingleDataList() {
      return singleData_;
    }
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    public java.util.List<? extends my.classes.MyDataSet.SingleDataOrBuilder> 
        getSingleDataOrBuilderList() {
      return singleData_;
    }
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    public int getSingleDataCount() {
      return singleData_.size();
    }
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    public my.classes.MyDataSet.SingleData getSingleData(int index) {
      return singleData_.get(index);
    }
    /**
     * <code>repeated .SingleData singleData = 1;</code>
     */
    public my.classes.MyDataSet.SingleDataOrBuilder getSingleDataOrBuilder(
        int index) {
      return singleData_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < singleData_.size(); i++) {
        output.writeMessage(1, singleData_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < singleData_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, singleData_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof my.classes.MyDataSet.DataSet)) {
        return super.equals(obj);
      }
      my.classes.MyDataSet.DataSet other = (my.classes.MyDataSet.DataSet) obj;

      boolean result = true;
      result = result && getSingleDataList()
          .equals(other.getSingleDataList());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getSingleDataCount() > 0) {
        hash = (37 * hash) + SINGLEDATA_FIELD_NUMBER;
        hash = (53 * hash) + getSingleDataList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static my.classes.MyDataSet.DataSet parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static my.classes.MyDataSet.DataSet parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static my.classes.MyDataSet.DataSet parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static my.classes.MyDataSet.DataSet parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(my.classes.MyDataSet.DataSet prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DataSet}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DataSet)
        my.classes.MyDataSet.DataSetOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return my.classes.MyDataSet.internal_static_DataSet_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return my.classes.MyDataSet.internal_static_DataSet_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                my.classes.MyDataSet.DataSet.class, my.classes.MyDataSet.DataSet.Builder.class);
      }

      // Construct using my.classes.MyDataSet.DataSet.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSingleDataFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (singleDataBuilder_ == null) {
          singleData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          singleDataBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return my.classes.MyDataSet.internal_static_DataSet_descriptor;
      }

      public my.classes.MyDataSet.DataSet getDefaultInstanceForType() {
        return my.classes.MyDataSet.DataSet.getDefaultInstance();
      }

      public my.classes.MyDataSet.DataSet build() {
        my.classes.MyDataSet.DataSet result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public my.classes.MyDataSet.DataSet buildPartial() {
        my.classes.MyDataSet.DataSet result = new my.classes.MyDataSet.DataSet(this);
        int from_bitField0_ = bitField0_;
        if (singleDataBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            singleData_ = java.util.Collections.unmodifiableList(singleData_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.singleData_ = singleData_;
        } else {
          result.singleData_ = singleDataBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof my.classes.MyDataSet.DataSet) {
          return mergeFrom((my.classes.MyDataSet.DataSet)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(my.classes.MyDataSet.DataSet other) {
        if (other == my.classes.MyDataSet.DataSet.getDefaultInstance()) return this;
        if (singleDataBuilder_ == null) {
          if (!other.singleData_.isEmpty()) {
            if (singleData_.isEmpty()) {
              singleData_ = other.singleData_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureSingleDataIsMutable();
              singleData_.addAll(other.singleData_);
            }
            onChanged();
          }
        } else {
          if (!other.singleData_.isEmpty()) {
            if (singleDataBuilder_.isEmpty()) {
              singleDataBuilder_.dispose();
              singleDataBuilder_ = null;
              singleData_ = other.singleData_;
              bitField0_ = (bitField0_ & ~0x00000001);
              singleDataBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getSingleDataFieldBuilder() : null;
            } else {
              singleDataBuilder_.addAllMessages(other.singleData_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        my.classes.MyDataSet.DataSet parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (my.classes.MyDataSet.DataSet) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<my.classes.MyDataSet.SingleData> singleData_ =
        java.util.Collections.emptyList();
      private void ensureSingleDataIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          singleData_ = new java.util.ArrayList<my.classes.MyDataSet.SingleData>(singleData_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          my.classes.MyDataSet.SingleData, my.classes.MyDataSet.SingleData.Builder, my.classes.MyDataSet.SingleDataOrBuilder> singleDataBuilder_;

      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public java.util.List<my.classes.MyDataSet.SingleData> getSingleDataList() {
        if (singleDataBuilder_ == null) {
          return java.util.Collections.unmodifiableList(singleData_);
        } else {
          return singleDataBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public int getSingleDataCount() {
        if (singleDataBuilder_ == null) {
          return singleData_.size();
        } else {
          return singleDataBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public my.classes.MyDataSet.SingleData getSingleData(int index) {
        if (singleDataBuilder_ == null) {
          return singleData_.get(index);
        } else {
          return singleDataBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder setSingleData(
          int index, my.classes.MyDataSet.SingleData value) {
        if (singleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSingleDataIsMutable();
          singleData_.set(index, value);
          onChanged();
        } else {
          singleDataBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder setSingleData(
          int index, my.classes.MyDataSet.SingleData.Builder builderForValue) {
        if (singleDataBuilder_ == null) {
          ensureSingleDataIsMutable();
          singleData_.set(index, builderForValue.build());
          onChanged();
        } else {
          singleDataBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder addSingleData(my.classes.MyDataSet.SingleData value) {
        if (singleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSingleDataIsMutable();
          singleData_.add(value);
          onChanged();
        } else {
          singleDataBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder addSingleData(
          int index, my.classes.MyDataSet.SingleData value) {
        if (singleDataBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureSingleDataIsMutable();
          singleData_.add(index, value);
          onChanged();
        } else {
          singleDataBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder addSingleData(
          my.classes.MyDataSet.SingleData.Builder builderForValue) {
        if (singleDataBuilder_ == null) {
          ensureSingleDataIsMutable();
          singleData_.add(builderForValue.build());
          onChanged();
        } else {
          singleDataBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder addSingleData(
          int index, my.classes.MyDataSet.SingleData.Builder builderForValue) {
        if (singleDataBuilder_ == null) {
          ensureSingleDataIsMutable();
          singleData_.add(index, builderForValue.build());
          onChanged();
        } else {
          singleDataBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder addAllSingleData(
          java.lang.Iterable<? extends my.classes.MyDataSet.SingleData> values) {
        if (singleDataBuilder_ == null) {
          ensureSingleDataIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, singleData_);
          onChanged();
        } else {
          singleDataBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder clearSingleData() {
        if (singleDataBuilder_ == null) {
          singleData_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          singleDataBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public Builder removeSingleData(int index) {
        if (singleDataBuilder_ == null) {
          ensureSingleDataIsMutable();
          singleData_.remove(index);
          onChanged();
        } else {
          singleDataBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public my.classes.MyDataSet.SingleData.Builder getSingleDataBuilder(
          int index) {
        return getSingleDataFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public my.classes.MyDataSet.SingleDataOrBuilder getSingleDataOrBuilder(
          int index) {
        if (singleDataBuilder_ == null) {
          return singleData_.get(index);  } else {
          return singleDataBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public java.util.List<? extends my.classes.MyDataSet.SingleDataOrBuilder> 
           getSingleDataOrBuilderList() {
        if (singleDataBuilder_ != null) {
          return singleDataBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(singleData_);
        }
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public my.classes.MyDataSet.SingleData.Builder addSingleDataBuilder() {
        return getSingleDataFieldBuilder().addBuilder(
            my.classes.MyDataSet.SingleData.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public my.classes.MyDataSet.SingleData.Builder addSingleDataBuilder(
          int index) {
        return getSingleDataFieldBuilder().addBuilder(
            index, my.classes.MyDataSet.SingleData.getDefaultInstance());
      }
      /**
       * <code>repeated .SingleData singleData = 1;</code>
       */
      public java.util.List<my.classes.MyDataSet.SingleData.Builder> 
           getSingleDataBuilderList() {
        return getSingleDataFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          my.classes.MyDataSet.SingleData, my.classes.MyDataSet.SingleData.Builder, my.classes.MyDataSet.SingleDataOrBuilder> 
          getSingleDataFieldBuilder() {
        if (singleDataBuilder_ == null) {
          singleDataBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              my.classes.MyDataSet.SingleData, my.classes.MyDataSet.SingleData.Builder, my.classes.MyDataSet.SingleDataOrBuilder>(
                  singleData_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          singleData_ = null;
        }
        return singleDataBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:DataSet)
    }

    // @@protoc_insertion_point(class_scope:DataSet)
    private static final my.classes.MyDataSet.DataSet DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new my.classes.MyDataSet.DataSet();
    }

    public static my.classes.MyDataSet.DataSet getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DataSet>
        PARSER = new com.google.protobuf.AbstractParser<DataSet>() {
      public DataSet parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DataSet(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DataSet> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DataSet> getParserForType() {
      return PARSER;
    }

    public my.classes.MyDataSet.DataSet getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_SingleData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_SingleData_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DataSet_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DataSet_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\017mydataset.proto\"F\n\nSingleData\022\020\n\010someT" +
      "ext\030\001 \001(\t\022\021\n\tsomeValue\030\002 \001(\005\022\023\n\013timeSeco" +
      "nds\030\003 \001(\003\"*\n\007DataSet\022\037\n\nsingleData\030\001 \003(\013" +
      "2\013.SingleDataB\027\n\nmy.classesB\tMyDataSetb\006" +
      "proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_SingleData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_SingleData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_SingleData_descriptor,
        new java.lang.String[] { "SomeText", "SomeValue", "TimeSeconds", });
    internal_static_DataSet_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_DataSet_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DataSet_descriptor,
        new java.lang.String[] { "SingleData", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
